name: Run test

on:
  pull-request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: composer-php
        uses: nick-zh/composer@php7.4
        with:
          php-version: 8.3



